const session=requireRole('manager');
document.getElementById('welcomeName').textContent='Hi, '+session.name.split(' ')[0];document.getElementById('managerRestaurantName').textContent=session.restaurant;
const STATUS_BADGE_CLASS={Placed:'badge-placed',Accepted:'badge-preparing',Preparing:'badge-preparing','Ready for Pickup':'badge-ready','Out for Delivery':'badge-transit',Delivered:'badge-delivered'};
const NEXT={Placed:['Accepted','Accept order'],Accepted:['Preparing','Start preparing'],Preparing:['Ready for Pickup','Mark ready for pickup']};
document.querySelectorAll('.tab-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('ordersTab').classList.toggle('hidden',b.dataset.tab!=='orders');document.getElementById('menuTab').classList.toggle('hidden',b.dataset.tab!=='menu');});
function restaurantOrders(){return DB.getOrders().filter(o=>o.restaurant===session.restaurant)}
function renderStats(){const o=restaurantOrders(),sales=o.reduce((s,x)=>s+(x.status!=='Placed'?x.total:0),0),avgItems=DB.getMenu().filter(i=>i.restaurant===session.restaurant).reduce((s,i)=>s+(i.rating||4.5),0)/(DB.getMenu().filter(i=>i.restaurant===session.restaurant).length||1);document.getElementById('statOrders').textContent=o.length;document.getElementById('statPreparing').textContent=o.filter(x=>x.status==='Preparing'||x.status==='Accepted').length;document.getElementById('statReady').textContent=o.filter(x=>x.status==='Ready for Pickup').length;document.getElementById('statSales').textContent='₹'+sales;document.getElementById('statRating').textContent='★ '+avgItems.toFixed(1)}
function renderOrders(){const o=restaurantOrders(),c=document.getElementById('ordersContainer');if(!o.length){c.innerHTML=`<div class="empty"><strong>No orders for ${escapeHtml(session.restaurant)}</strong>Only this restaurant's orders are visible to you.</div>`;renderStats();return}c.innerHTML=o.map(x=>{const next=NEXT[x.status];return `<div class="card order-row"><div class="info"><div class="flex-between"><span style="font-weight:600">Order #${x.id.slice(-5)} · ${escapeHtml(x.customerName)}</span><span class="badge ${STATUS_BADGE_CLASS[x.status]}">${x.status}</span></div><div class="items">${escapeHtml(x.items.map(i=>`${i.name} ×${i.qty}`).join(', '))}</div><div class="meta">${escapeHtml(x.address)} · ₹${x.total} · ${new Date(x.placedAt).toLocaleString()}${x.deliveryPartnerEmail?' · Partner: '+escapeHtml(x.deliveryPartnerEmail):''}</div></div><div class="order-actions">${next?`<button class="btn btn-basil btn-small" onclick="advanceStatus('${x.id}')">${next[1]}</button>`:`<span style="font-size:12.5px;color:var(--muted)">${x.status==='Delivered'?'Completed':'With delivery partner'}</span>`}</div></div>`}).join('');renderStats()}
function advanceStatus(id){const o=restaurantOrders().find(x=>x.id===id);if(!o||!NEXT[o.status])return;DB.updateOrder(id,{status:NEXT[o.status][0]});renderOrders()}
function renderMenu(){const menu=DB.getMenu().filter(i=>i.restaurant===session.restaurant),body=document.getElementById('menuTableBody');body.innerHTML=menu.length?menu.map(i=>`<tr><td><img src="${escapeAttr(i.image)}" class="mini-food" alt="${escapeHtml(i.name)}"></td><td>${escapeHtml(i.name)}</td><td>${i.type==='veg'?'Veg':'Non-veg'}</td><td>₹${i.price}</td><td>★ ${(i.rating||4.5).toFixed(1)}</td><td><span class="badge ${i.available===false?'badge-placed':'badge-delivered'}">${i.available===false?'Out of stock':'Available'}</span></td><td><button class="btn btn-outline btn-small" onclick="editItem('${i.id}')">Edit</button> <button class="btn btn-outline btn-small" onclick="toggleAvailability('${i.id}')">${i.available===false?'Enable':'Out of stock'}</button></td></tr>`).join(''):'<tr><td colspan="7">No dishes yet.</td></tr>'}
document.getElementById('addItemForm').onsubmit=e=>{e.preventDefault();const name=itemName.value.trim(),price=Number(itemPrice.value),type=itemType.value,image=itemImage.value.trim(),banner=restaurantBanner.value.trim();if(!name||!price||!image){alert('Enter dish name, price and food image URL.');return}const menu=DB.getMenu();menu.push({id:'m_'+Date.now(),restaurant:session.restaurant,name,price,type,category:itemCategory.value.trim(),image,bannerImage:banner||getCurrentBanner(),rating:4.5,available:true});DB.saveMenu(menu);e.target.reset();renderMenu()}
function getCurrentBanner(){return DB.getMenu().find(i=>i.restaurant===session.restaurant)?.bannerImage||''}
function editItem(id){const menu=DB.getMenu(),i=menu.find(x=>x.id===id);if(!i)return;const n=prompt('Food item name:',i.name);if(n===null)return;const p=prompt('Price:',i.price);if(p===null)return;const img=prompt('Food image URL (img src):',i.image);if(img===null)return;const banner=prompt('Restaurant banner image URL (img src):',i.bannerImage);if(banner===null)return;i.name=n.trim()||i.name;i.price=Number(p)||i.price;i.image=img.trim()||i.image;const b=banner.trim()||i.bannerImage;menu.filter(x=>x.restaurant===session.restaurant).forEach(x=>x.bannerImage=b);DB.saveMenu(menu);renderMenu()}
function toggleAvailability(id){const menu=DB.getMenu(),i=menu.find(x=>x.id===id);if(!i)return;i.available=i.available===false;DB.saveMenu(menu);renderMenu()}
function deleteItem(id){DB.saveMenu(DB.getMenu().filter(i=>i.id!==id));renderMenu()}
renderOrders();renderMenu();window.addEventListener('storage',()=>{renderOrders();renderMenu()});
